kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-secure-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: slow
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi